print("For logging in, find Username & password by giving wrong inputs \nBest Of Luck!!!")

import time

def account():
    name = str(input("What's your name pal?? "))
    pp = "Wow, so funny name, " + name + "!! Hahaha \nGo Ahead"
    print(pp)
    time.sleep(2)
    print("Instructions:")
    time.sleep(1)
    print("Only 1 or 2, there are just two choices...")
    time.sleep(2)
    print("Please don't use your genius brain to enter any alphabet or...")
    time.sleep(2)
    print("See what happens....")
    print("Ok??")
    time.sleep(1)
    a = str(input("Choose 1 to create an account and 2 to login to an existing account: "))
    try:    
        if a == '1':
            print("Oo, so you don't have an account. \nPoor Guy!!")
            time.sleep(1)
            b = str(input("Enter your username: "))
            if len(b) > 15:
                print("Username too long, you wanna crash the server?! max 15 digits!")
            elif len(b) < 3:
                print("Username too short mate! Better Luck Next Time! \nMin 3 characters!")
            else:
                print("Username selected is: " + b)
                time.sleep(0.5)
                c = str(input("Enter your password (Min 5 characters): "))
                if len(c) > 15:
                    print("Password too long! Max 15 characters")
                elif len(c) < 5:
                    print("Password too short! \nI just told ya...")
                    time.sleep(1)
                    print("And you're a genius leaving your password so easy so that I can hack your computer and upload your browsing history (You know what I mean) and make it viral...")
                    time.sleep(6)
                    print("I'm kidding I don't know what the heck is hacking \nMin 5 characters")
                    time.sleep(0.5)
                else:
                    d = input("Confirm Your Password: ")
                    if c != d:
                        print("Password didn't matched! \nFor extra security (Or due to lack of my coding skills), Restart the whole process!")
                    else:
                        print("Your Password is '" + d + "'.")
                        time.sleep(0.5)
                        print("Note it down somewhere because I know you'll forget it now or later, Okk??")
                        time.sleep(1)
                        e = input("Confirm Account Creation?? Y/N: ")
                        if e == 'Y' or e == 'y':
                            print("Account Created Unsuccesfully!")
                            time.sleep(1)
                            print("I saw someone behind you is spying on you! \nBe careful!!")
                            time.sleep(2)
                            print("Now you cannot create account because it's my code and I do whatever I want!!")
                            time.sleep(2)
                            ok = input("Is that Ok?? ")
                            print("I don't care")
                        elif e == 'N' or e == 'n':
                            print("Why the hell did you created username and password then??")
                            time.sleep(1.5)
                            print("You're too genius to be here!!")
                            time.sleep(1)
                            print("Byyy")
                            time.sleep(1)
                        else:
                            print("I asked Y or N you annoying kiddo!! What is this " + e + " Huh??")
        elif a == '2':
            print("You have an account!! \nGreat!!")
            time.sleep(0.5)
            b = input("Username: ")
            if b != 'Advik':
                print("Checking Username...")
                time. sleep(1)
                print("Server is listening Dubstep, wait a sec...")
                time.sleep(1.2)
                print("Beating the server to get the username...")
                time.sleep(1)
                print("Stealing usernames list and checking, wait one more sec")
                time.sleep(1)
                print("ERROR 404")
                time.sleep(1)
                print("Invalid Username! \nThere's only one username and that is...")
                time.sleep(1.2)
                print("Advik \nGoto Hell Now \nHappy Journey!!")
                time. sleep(2)
            elif b == 'Advik':
                print("Checking Username...")
                time.sleep(2)
                print('User exists!! \nWow!!!')
                c = input("Enter your password: ")
                if c != 'idkiamdumb':
                    print("Wrong Password you annoying kid!! \nNow we are coming to your home to shoot you down within 30 mins!!")
                    time.sleep(3)
                    print("RIP Mr/Mrs(Whatever) " + name + ". The Password is idkiamdumb (I mean you're dumb) \nTry Again, what if you logged in and gained access to secret database, who knows...")
                    time.sleep(7)
                elif c == 'idkiamdumb':
                    print("You knew the Password!! \nGreat job pal!!")
                    time.sleep(0.5)
                    print("Checking Your Location...")
                    time.sleep(1)
                    print("Getting Permissions if you can be logged in...")
                    time.sleep(2)
                    print("Permission Denied \nKilling Server's Boss with a Donut...")
                    time.sleep(2)
                    print("Got Trapped...")
                    time.sleep(1.5)
                    print("I'm arrested! Save me by dropping $59816 at my doorstep or wait till they release me...")
                    time.sleep(3)
                    print("Access Denied! \nLogin Error")
                    time.sleep(2)
                    print("Try creating your account with another Username...")
        else:
            print("Just two choices, 1 or 2 and you're so genius that you typed " + a + ". Wow!! IQ x100")
            time.sleep(5)
            print("I'm amazed!! \nRIP Coding \nRIP Understanding \nRIP me \nRIP " + name + "! Hahaha, now you're going to die!!")
            time.sleep(5)
            print("Wait 10 seconds for some amazing Surprise for a genius guy like you!!")
            time.sleep(4)
            print(10)
            time.sleep(1)
            print(9)
            time.sleep(1)
            print(8)
            time.sleep(1)
            print(7)
            time.sleep(1)
            print(6)
            time.sleep(1)
            print(5)
            time.sleep(1)
            print(4)
            time.sleep(1)
            print(3.5)
            time.sleep(1)
            print(3)
            time.sleep(1)
            print(2)
            time.sleep(1)
            print(1)
            time.sleep(1)
            print(0)
            time.sleep(1)
            print("We're having problems with our server!!")
            time.sleep(2)
            print("No I'm Kidding, I don't even have a server!")
            time.sleep(2)
            print("I just wasted your so much time and I'm happy that You're as depressed as me:)")
            time.sleep(2.5)
            print("We're programmers, We never Smile, we just Cry!!!")
            time.sleep(2)
            print("Share this code with your programmer friends and let them feel the pain \nLMAO")
    except:
        print("You're a dumb guy, you caused an error!!")
    finally:
        print("   ")
        time.sleep(1)
        print("This is my first code with over 4 stars (now 5) (now 6) (now 7) \n(now 8) (now 9) (now 10) (now 11) (now 12) (now 13)\n(now 15) (now 16) (and now 19) (26, You guys on fire??) (27 & so on... I'm tired updating :D)")
        time.sleep(2.6)
        print("And over 5 forks! (now 7) (and now 9) (Wow, and now 13!) (15 and ...)")
        time.sleep(2)
        print("Thank You So Much for the Support!!")
        time.sleep(2)
        print("Did you tried giving wrong inputs??")
        
account()